### ISSUE TITLE
TypeError: Cannot read property 'action' of undefined

### ISSUE THREAD

**Issue by mrchief** [probot/serverless-lambda#15]
The code at https://github.com/probot/serverless-lambda/blob/master/index.js#L51 doesn't account for cases where `event.body` could be absent (e.g. using custom routes).

I think a check for `event.body.action` would at least avoid this error. 

A better fix would be to account for other routes and invoke `next()` instead of trying to handle it within probot.

<details>
  <summary><b>Stack trace</b></summary>  

```
  at <path/to/repo>\node_modules\@probot\serverless-lambda\index.js:51:50
    at nameSpace.run (<path/to/repo>\node_modules\node-lambda\lib\main.js:125:22)
    at Namespace.run (<path/to/repo>\node_modules\continuation-local-storage\context.js:48:5)
    at Lambda._runHandler (<path/to/repo>\node_modules\node-lambda\lib\main.js:123:15)
    at Lambda.run (<path/to/repo>\node_modules\node-lambda\lib\main.js:84:10)
    at Command.program.command.alias.description.option.option.option.option.option.option.option.option.action (<path/to/repo>\node_modules\node-lambda\bin\node-lambda:138:27)
    at Command.listener (<path/to/repo>\node_modules\commander\index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (<path/to/repo>\node_modules\commander\index.js:654:12)
    at Command.parse (<path/to/repo>\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (<path/to/repo>\node_modules\node-lambda\bin\node-lambda:149:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

</details>

**Comment by JasonEtco** [comment]
Can you tell us more about your use-case? This is intended to be specifically for Probot apps, so I'm not sure why you'd need to account for cases where `event.body` is absent, it would _always_ be present for GitHub-sent events. If you're looking to use one function to support multiple routes, you should probably be using multiple functions instead.

**Comment by mrchief** [comment]
They are not new functions, rather routes for things like health checks, statuses etc.

It seems that probot supports it https://probot.github.io/docs/http/. 

Also, one can configure probot to receive events at a specific route via [`WEBHOOK_PATH`](https://probot.github.io/docs/configuration/) env var, so this error would happen for those cases as well.

In another case, I'm trying to port an existing app, and need to support existing routes: https://github.com/ewolfe/prlint/blob/feat/probot-app/src/routes.js.

Finally, as I was writing this reply, I'm seeing [this note from readme](https://github.com/probot/serverless-lambda#only-responds-to-webhooks-from-github) in a new light. :) 

It'd be nice if you can support these, if not I'll try to follow the recommendation specified in the readme.

**Comment by JasonEtco** [comment]
Yeah, that link to the README makes sense. I think its important to keep this extension very scoped - to follow standard FaaS architecture patterns, and to ensure that we're not shipping unnecessary code (in serverless functions, bundle sizes counts towards execution speed). I'm going to close this issue because I think your question is answered but feel free to reopen if I'm mistaken!

**Comment by mrchief** [comment]
Can't argue with bundle size and execution speed arguments! :)

I think in the very least, we should at least add prominent warnings in the readme about using custom routes or using `WEBHOOK_PATH` env var.

**Comment by JasonEtco** [comment]
Couldn't hurt - PRs welcome @mrchief ❤️
