### ISSUE TITLE
TypeError: Cannot read property 'wrap' of undefined

### ISSUE THREAD

**Issue by bdougie** [probot/serverless-lambda#3]
## Issue

I am testing out the serverless-lambda plugin using what is currently on npm:
```
npm i @probot/serverless-lambda
```
It seems to fail when trying to connect to probot and auth

## Error

```sh
ERROR event: Cannot read property 'wrap' of undefined
  TypeError: Cannot read property 'wrap' of undefined
      at Application.<anonymous> (/var/task/node_modules/probot/lib/application.js:253:57)
      at step (/var/task/node_modules/probot/lib/application.js:40:23)
      at Object.next (/var/task/node_modules/probot/lib/application.js:21:53)
      at /var/task/node_modules/probot/lib/application.js:15:71
      at new Promise (<anonymous>)
      at __awaiter (/var/task/node_modules/probot/lib/application.js:11:12)
      at Application.auth (/var/task/node_modules/probot/lib/application.js:237:16)
      at Application.<anonymous> (/var/task/node_modules/probot/lib/application.js:183:59)
      at step (/var/task/node_modules/probot/lib/application.js:40:23)
      at Object.next (/var/task/node_modules/probot/lib/application.js:21:53)
      at /var/task/node_modules/probot/lib/application.js:15:71
      at new Promise (<anonymous>)
      at __awaiter (/var/task/node_modules/probot/lib/application.js:11:12)
      at EventEmitter.<anonymous> (/var/task/node_modules/probot/lib/application.js:167:72)
      at Promise.all.handlers.map.handler (/var/task/node_modules/promise-events/emitter.js:125:28)
      at Array.map (<anonymous>)
      at EventEmitter.emit (/var/task/node_modules/promise-events/emitter.js:123:40)
      at Application.<anonymous> (/var/task/node_modules/probot/lib/application.js:100:37)
      at step (/var/task/node_modules/probot/lib/application.js:40:23)
      at Object.next (/var/task/node_modules/probot/lib/application.js:21:53)
      at /var/task/node_modules/probot/lib/application.js:15:71
      at new Promise (<anonymous>)
      at __awaiter (/var/task/node_modules/probot/lib/application.js:11:12)
      at Application.receive (/var/task/node_modules/probot/lib/application.js:90:16)
      at /var/task/node_modules/@probot/serverless-lambda/index.js:57:19
  --
  event: {
    "event": "issues.opened",
    "installation": 348774,
    "repository": "bdougie/bot-test-repo"
  }

```
I am currently catching an error from [app.receive](https://github.com/probot/serverless-lambda/blob/master/index.js#L67-L69). It seems like it is trying to call wrap on `this.cache`. I discovered this while digging through the compiled JavaScript file in the installed node_module.

## My attempt at a fix
I took at look the uncompiled TypeScript file where the error is coming from is here: https://github.com/probot/probot/blob/782707af676721e8722dc39dc53b6a89b7032171/src/application.ts#L216. 
```js
// node_modules/probot/lib/application.js

var Application = /** @class */ (function () {
    function Application(options) {
        var opts = options || {};
        this.cache = opts.cache;
       ...
    }

...

  Application.prototype.auth = function (id, log) {
        if (log === void 0) { log = this.log; }
        return __awaiter(this, void 0, void 0, function () {
            var github, installationTokenTTL, res;
            var _this = this;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        if (process.env.GHE_HOST && /^https?:\/\//.test(process.env.GHE_HOST)) {
                            throw new Error('Your \`GHE_HOST\` environment variable should not begin with https:// or http://');
                        }
                        github = github_1.GitHubAPI({
                            baseUrl: process.env.GHE_HOST && "https://" + process.env.GHE_HOST + "/api/v3",
                            debug: process.env.LOG_LEVEL === 'trace',
                            logger: log.child({ name: 'github', installation: String(id) })
                        });
                        installationTokenTTL = parseInt(process.env.INSTALLATION_TOKEN_TTL || '3540', 10);
                        if (!id) return [3 /*break*/, 2];
  ERROR HAPPENS HERE   ----->           return [4 /*yield*/, this.cache.wrap("app:" + id + ":token", function () {
                                log.trace("creating token for installation");
                                github.authenticate({ type: 'app', token: _this.app() });
                                return github.apps.createInstallationToken({ installation_id: String(id) });
                            }, { ttl: installationTokenTTL })];
                    case 1:
                        res = _a.sent();
                        github.authenticate({ type: 'token', token: res.data.token });
                        return [3 /*break*/, 3];
                    case 2:
                        github.authenticate({ type: 'app', token: this.app() });
                        _a.label = 3;
                    case 3: return [2 /*return*/, github];
                }
            });
        });
    };
    return Application;

```
This is my first time working with TypeScript and digging into the Probot source, not entirley what is exactly going on.

I did attempt to manually pass options, but it still seems like the Cache is still undefined.
```js
    await app.receive({
          name: e,
          payload: event.body,
       +  options: {ttl: 100}
     })
```

## Help
Curious if anyone can point me towards the solution and if I am at all close to thinking this `this.cache` is the issue. Even an explanation on how the `Cache` is being leveraged in Probot would help. 🙏🏾

```js
// node_modules/probot/lib/application.d.ts

export declare class Application {
    cache: Cache;
  ...
}
...
export interface Cache {
    wrap<T>(key: string, wrapper: (callback: (error: any, result: T) => void) => any, options: CacheConfig): Promise<any>;
}
```

cc/ @tcbyrd

**Comment by bdougie** [comment]
It seems like I was able to get past the original error by doing the following:

```
const cacheManager = require('cache-manager')

let memoryCache = cacheManager.caching({store: 'memory', max: 100, ttl: 10/*seconds*/});

...

const loadProbot = (plugin) => {
  app = app || new Application({
    id: process.env.APP_ID,
    secret: process.env.WEBHOOK_SECRET,
    cert: findPrivateKey(),
    cache: memoryCache
  })

```

This does not solve my overall issue of getting my app working in a serverless environment. Curious if there is suppose to be fallbacks for the options being created. It seems odd that a plugin would need all options passed through.

**Comment by tcbyrd** [comment]
> It seems odd that a plugin would need all options passed through.

Yeh, this is one of the problems we want to solve with https://github.com/probot/probot/issues/599

Right now you do have to provide these options:

https://github.com/probot/probot/blob/fc992466cc14ab15ee4439df4a686cc4f8dc8cbc/src/application.ts#L29-L37
```typescript
  constructor (options?: Options) {
    const opts = options || {} as any
    this.events = new EventEmitter()
    this.log = wrapLogger(logger, logger)
    this.app = opts.app
    this.cache = opts.cache
    this.catchErrors = opts.catchErrors || false
    this.router = opts.router || express.Router() // you can do this?
  }
```

Part of the goal of the plugin is to abstract all this away, because this is currently handled by `probot run` in normal node servers.

I'll get a fix published to npm tonight.
